name: blue
description: Just an app


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
build_runner: ^1.7.2
build_test: ^0.10.12
build_web_compilers: ^2.7.1

flutter:
  uses-material-design: true

  assets:
    - icons/
    - images/